##############################################
################# HA CHORES ##################
##############################################
home_chores_tracker:
  csv_path: "/config/sample_chore_data.csv"