##############################################
################# HA CHORES ##################
##############################################
home_chores_tracker:
  csv_path: "/homeassistant/config/sample_chore_data.csv"

